version: '3.8'
services:
  todo:
    image: node:20-alpine
    restart: always
    working_dir: /
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./backend:/server
      - ./frontend:/frontend

    command: [sh, -c, "cd server && npm run start:docker & cd ../frontend && npm run start"]
    links:
      - mongo

  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - ./mongodb:/data/db
