version: '3.8'
services:
  node:
    image: node:20-alpine
    restart: always
    working_dir: /
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/server

    command: [sh, -c, "cd server && npm install && npx ts-node-dev --respawn ./server/index.ts"]
    links:
      - mongo

  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - ./mongodb:/data/db
