version: '3.8'
services:
  todo:
    image: node:20-alpine
    restart: always
    working_dir: /
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./backend:/server
      - ./frontend/vuejs:/frontend/vuejs

    command: [sh, -c, "cd server && npm run start:docker & cd ../frontend/vuejs && npm i && npm run dev"]
    links:
      - mongo
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.125'
          memory: 128M


  mongo:
    image: mongo
    logging:
      driver: none
    volumes:
      - ./mongodb:/data/db
